name: Renovate

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Get Pull Requests
        id: pr
        run: |
          echo "$(gh pr list -s open -F json)" >> pr_data.json
          echo "::set-env name=PULL_REQUESTS::pr_data.json"

      - name: Perform Automatic Merge
        run: |
          pulls=$(cat $PULL_REQUESTS | jq -r '.[].number')
          for pr in $pulls; do
            gh pr merge $pr --merge
          done
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN }}
